### ISSUE TITLE
Naming issue

### ISSUE THREAD

**Issue by valdo404** [gillius/jfxutils#23]
https://github.com/gillius/jfxutils/blob/49616f5954e6d64bc9e6bc9e89dfaad32627eee3/jfxutils/src/main/java/org/gillius/jfxutils/chart/AxisTickFormatter.java#L28

Hey, according to the content of the file, maybe the file should be renamed AxisTickLabelFormatter.java ?

What do you think ?

**Comment by gillius** [comment]
Changing the name of the interface will be a compile-time and runtime breaking change for users. So, unless the interface's name was overly confusing to users, I think it should be left as-is. If the issue is minor, we could address the issue by improving the documentation on the interface. Did this naming result in wasted time trying to use the library, and if so, do you have a proposal for an improved documentation?

**Comment by valdo404** [comment]
I think it would  be better to let it as is. Best
